### ISSUE TITLE
Linking a node to multiple other nodes of the same type in one transaction

### ISSUE THREAD

**Issue by Errol-Hassall** [ospaarmann/exdgraph#11]
I have a database of people off those people I have a year node that will contain all the friendships they have. Using the map notation I can link the year node to a pre-exisiting person using the uid. But when it comes time to link them to multiple people it doesnt work. It will take what ever the second friend is and link them to that, overriding the first one. 
`map = %{
      uid: "0x#{attrs[:person_id]}",
      person_id: "#{attrs[:person_id]}",
      name:  "#{attrs[:person_id]}",
      type: "person",
      
      year: %{
        name: "#{year}",
        friends: %{
          uid: "0x#{attrs[:friend1]}",
        },
        friends: %{
          uid: "0x#{attrs[:friend2]}",
        },
      },
    }`
This will link the node to friend2 but not friend1 and if I then add a third friend it will add it to friend3. 
The end result would be person has edges from the year to 6 different friends.
Using this map notation is it possible to add multiple edges two the same type of node at once?

**Comment by ospaarmann** [comment]
As I understand the year node already exists. Correct? If you want to reference and change a node, you have to set the uid in the map. Otherwise a new node will be created every time. Try setting the uid in year.

**Comment by Errol-Hassall** [comment]
Yeah i've figured it out, i wasnt using the right syntax so now i can grab the uid and then assign it to that uid as a friend

**Comment by ospaarmann** [comment]
So I consider this one solved.
