### ISSUE TITLE
Readme web endpoint docs overkill

### ISSUE THREAD

**Issue by rdrey** [ospaarmann/exdgraph#12]
How do you feel about removing the section about SSL certs for the HTTP endpoint? 

I think the deps section for phoenix adds value, as do the SSL/TLS sections for the connection to dgraph.

But I was a little confused by the section describing the changes to the web endpoint. It seems mandatory to switch to the `Cowboy2Handler`, but my app is working fine as is.

**Comment by ospaarmann** [comment]
Thanks for the feedback. I will clean up the Readme. It was growing on the go and I will move some sections to the Wiki.

**Comment by ospaarmann** [comment]
I decided against removing it because it is helpful for some people and if not you can just skip it. I will move more things into the Wiki though over time.
