### ISSUE TITLE
is it possible to add edge attributes using the map syntax?

### ISSUE THREAD

**Issue by Errol-Hassall** [ospaarmann/exdgraph#13]
I need to add some edge attributes, is it possible to add those using the easier to use map notation?

**Comment by ospaarmann** [comment]
Hey, this should be possible following the JSON examples in the docs: https://docs.dgraph.io/mutations/#facets

You can do something like:

```elixir
%{
  name: "Carol",
  "name|initial": "C",
  friend: %{
    name: "Daryl",
    "friend|close": "yes"
  }
}
```

**Comment by Errol-Hassall** [comment]
Thats cool as, I'll give that a try thank you
