### ISSUE TITLE
Allow ability to set context deadline for GRPC calls

### ISSUE THREAD

**Issue by emhagman** [ospaarmann/exdgraph#18]
See:
https://github.com/tony612/grpc-elixir/blob/b635aff233e8db173557e9eca414bc9d640e71d7/test/grpc/integration/stub_test.exs

Also see:
https://discuss.dgraph.io/t/dgraph-java-client-setting-deadlines-per-call/3056

And also why we should be able to pass it in:
https://grpc.io/blog/deadlines

**Comment by ospaarmann** [comment]
Hey,

this makes sense to me. For me personally it makes more sense to focus first on supporting transactions. But if you want to enable context deadlines, feel free to submit a PR. I would just ask you to

- outline here how you plan to do it
- make it configurable and make sure, that the naming is not confusing (we already have `:timeout` which holds the value for the connection timeout)

Thanks!
Ole

**Comment by emhagman** [comment]
I agree I'd probably want to see transaction support first as well but I'll give this a shot.

**Comment by ospaarmann** [comment]
@emhagman I sometimes get the error 

```
{:error, [code: 2, message: "While proposing: context deadline exceeded"]}
```

back from Dgraph. So a context deadline is already set but not explicitly. This seems to be a performance issue and goes away when I reset Dgraph by deleting all data. So setting this explicitly from ExDgraph seems to be a very good idea 😉

**Comment by emhagman** [comment]
See https://github.com/ospaarmann/exdgraph/pull/24
